global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['gateway:8080']

  - job_name: 'discovery'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['discovery:8761']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8081']

  - job_name: 'study-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'study-service:8082']

  - job_name: 'progress-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'progress-service:8083']

  - job_name: 'cert-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['cert-service:8084']

  - job_name: 'versus-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['versus-service:8085']

  - job_name: 'community-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['community-service:8086']
